package tw.cmlove.taxiexam;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private BankStore store; private BankStore.Bank bank; private StudyState state;
    private LinearLayout root,content,nav; private FrameLayout area; private ScrollView scroll;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private int ink,muted,bg,surface,line; private final int yellow=Color.rgb(255,211,61),green=Color.rgb(25,133,100),red=Color.rgb(190,59,53);
    private String page="home",bankMode="all",bankCity="全部地區",search=""; private int bankType=0,bankPage=0;private boolean updating=false;
    private LinearLayout questionList;private TextView questionCount,timer; private StudyState.Session lastFinished;
    private interface Action {void run()throws Exception;}
    @Override public void onCreate(Bundle saved) {
        super.onCreate(saved);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        String restore=saved==null?"home":saved.getString("page","home");
        TextView loading=new TextView(this);loading.setText("計程車考照\n正在準備離線題庫…");loading.setTextSize(22);loading.setGravity(Gravity.CENTER);loading.setBackgroundColor(yellow);setContentView(loading);
        new Thread(()->{try{store=new BankStore(this);bank=store.load();state=new StudyState(this);runOnUiThread(()->{if(isDestroyed())return;buildShell();if(restore.equals("quiz")&&state.active!=null)quiz();else home();if(state.recovered)toast("部分舊紀錄無法讀取，已保留原始檔案。");if(System.currentTimeMillis()-state.data.optLong("lastCheck",0)>86400000L)updateBank(false);handler.post(tick);});}catch(Exception e){runOnUiThread(()->{loading.setText("題庫載入失敗\n"+e.getMessage());});}},"load-bank").start();
    }
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("page",page);}
    @Override protected void onPause(){super.onPause();if(state!=null)persist();}
    @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);super.onDestroy();}
    private final Runnable tick=new Runnable(){public void run(){if(state!=null&&state.active!=null&&page.equals("quiz")){long left=state.active.deadline-System.currentTimeMillis();if(state.active.exam&&left<=0){complete();}else if(timer!=null)timer.setText(state.active.exam?"剩餘 "+clock(left):"自由練習 · 不限時");}handler.postDelayed(this,1000);}};
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private String clock(long ms){long seconds=Math.max(0,ms/1000);return String.format(Locale.TAIWAN,"%02d:%02d",seconds/60,seconds%60);}
    private String date(long time){return new SimpleDateFormat("MM/dd HH:mm",Locale.TAIWAN).format(new Date(time));}
    private String bankDate(){try{return new SimpleDateFormat("yyyy/MM/dd HH:mm",Locale.TAIWAN).format(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX",Locale.ROOT).parse(bank.date));}catch(Exception e){return bank.date;}}
    private void toast(String message){Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
    private void persist(){try{state.save();}catch(Exception e){toast("紀錄暫時無法儲存，請檢查手機空間。");}}
    private void safely(Action action){try{action.run();}catch(Exception e){new AlertDialog.Builder(this).setTitle("請確認").setMessage(e.getMessage()==null?"操作無法完成，請重試。":e.getMessage()).setPositiveButton("知道了",null).show();}}
    private GradientDrawable shape(int color,int border){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(18));if(border!=0)d.setStroke(dp(1),border);return d;}
    private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(3),1);if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
    private void gap(LinearLayout parent,int height){View v=new View(this);parent.addView(v,new LinearLayout.LayoutParams(1,dp(height)));}
    private TextView label(LinearLayout parent,String value,int size,int color,boolean bold){TextView t=text(value,size,color,bold);parent.addView(t,new LinearLayout.LayoutParams(-1,-2));return t;}
    private LinearLayout row(LinearLayout parent){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);parent.addView(r,new LinearLayout.LayoutParams(-1,-2));return r;}
    private LinearLayout card(LinearLayout parent,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(shape(color,color==surface?line:0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);parent.addView(c,p);return c;}
    private Button button(LinearLayout parent,String caption,boolean primary,Action action){Button b=new Button(this);b.setText(caption);b.setAllCaps(false);b.setTextSize(16);b.setTextColor(primary?Color.rgb(24,31,33):ink);b.setTypeface(null,Typeface.BOLD);b.setBackground(shape(primary?yellow:surface,primary?0:line));b.setPadding(dp(12),dp(10),dp(12),dp(10));b.setMinHeight(dp(52));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(8);if(parent.getOrientation()==LinearLayout.HORIZONTAL){p.width=0;p.weight=1;p.leftMargin=dp(3);p.rightMargin=dp(3);}parent.addView(b,p);b.setOnClickListener(v->safely(action));return b;}
    private void palette(){boolean night=state.data.optBoolean("night");ink=Color.parseColor(night?"#F1F3F4":"#172022");muted=Color.parseColor(night?"#B0B8BD":"#667077");bg=Color.parseColor(night?"#111719":"#F6F7F5");surface=Color.parseColor(night?"#20292D":"#FFFFFF");line=Color.parseColor(night?"#344045":"#E0E5E3");}
    private void buildShell(){palette();root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);area=new FrameLayout(this);root.addView(area,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setPadding(dp(8),dp(6),dp(8),dp(8));nav.setBackgroundColor(surface);root.addView(nav,new LinearLayout.LayoutParams(-1,-2));setContentView(root);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(surface);getWindow().getDecorView().setSystemUiVisibility(state.data.optBoolean("night")?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});root.requestApplyInsets();}
    private void screen(String name,String title,String subtitle){page=name;timer=null;area.removeAllViews();scroll=new ScrollView(this);scroll.setFillViewport(true);area.addView(scroll,new FrameLayout.LayoutParams(-1,-1));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(22),dp(20),dp(24));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));label(content,title,27,ink,true);if(!subtitle.isEmpty()){gap(content,3);label(content,subtitle,13,muted,false);}gap(content,20);nav.removeAllViews();nav.setVisibility(name.equals("quiz")?View.GONE:View.VISIBLE);String[] labels={"首頁","題庫","車庫","我的"};String[] names={"home","bank","garage","me"};for(int i=0;i<labels.length;i++){final int index=i;Button b=button(nav,labels[i],names[i].equals(name),()->{if(index==0)home();else if(index==1){bankMode="all";bankPage=0;bank();}else if(index==2)garage();else me();});b.setTextSize(14);b.setMinHeight(dp(48));}}
    private void home(){screen("home","計程車考照","把每一次練習，變成上路的底氣。");LinearLayout hero=card(content,yellow);label(hero,"準備好，下一站出發。",24,Color.rgb(24,31,33),true);gap(hero,8);label(hero,"離線題庫・原生測驗・隨時接著練",14,Color.rgb(52,57,53),false);hero.addView(new TaxiView(this,false),new LinearLayout.LayoutParams(-1,dp(124)));LinearLayout stats=row(content);stat(stats,"已掌握",String.valueOf(state.earned.size()),"題");stat(stats,"待複習",String.valueOf(currentWrong().size()),"題");stat(stats,"金幣",String.valueOf(state.data.optInt("coins")),"枚");gap(content,16);
        if(state.active!=null){LinearLayout c=card(content,surface);label(c,"上次還沒完成",15,muted,false);label(c,state.active.title+" · "+(state.active.index+1)+" / "+state.active.questions.size(),18,ink,true);button(c,"繼續作答",true,()->quiz());}
        button(content,"開始模擬考",true,()->setup(true));button(content,"自由練習",false,()->setup(false));LinearLayout quick=row(content);button(quick,"錯題複習",false,()->{bankMode="wrong";bankCity="全部地區";bankType=0;search="";bankPage=0;bank();});button(quick,"每日 5 題挑戰",false,()->challenge());gap(content,22);
        LinearLayout source=card(content,surface);label(source,"手機內已有 "+bank.questions.size()+" 題",17,ink,true);gap(source,5);label(source,"題庫資料："+bankDate()+"\n來源：警政署題庫／你的網站更新檔",12,muted,false);button(source,updating?"正在檢查題庫…":"檢查題庫更新",false,()->updateBank(true));label(source,"離線可作答。連線時只下載題庫資料，更新失敗仍保留原題庫。",12,muted,false);
        label(content,"獨立開發的練習工具，非政府官方 App。",11,muted,false);
    }
    private void stat(LinearLayout parent,String title,String value,String unit){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(3),dp(13),dp(3),dp(13));box.setBackground(shape(surface,line));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(3),0,dp(3),0);parent.addView(box,p);TextView top=label(box,value,24,ink,true);top.setGravity(Gravity.CENTER);TextView bottom=label(box,title+" / "+unit,11,muted,false);bottom.setGravity(Gravity.CENTER);}
    private Spinner spinner(LinearLayout parent,String[] items,int selected){Spinner s=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,items){@Override public View getView(int position,View convert,ViewGroup parent){View v=super.getView(position,convert,parent);if(v instanceof TextView)((TextView)v).setTextColor(ink);return v;}@Override public View getDropDownView(int position,View convert,ViewGroup parent){View v=super.getDropDownView(position,convert,parent);v.setBackgroundColor(surface);if(v instanceof TextView)((TextView)v).setTextColor(ink);return v;}};adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(adapter);s.setSelection(Math.max(0,selected));s.setBackground(shape(surface,line));s.setPadding(dp(8),dp(8),dp(8),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.topMargin=dp(7);p.bottomMargin=dp(12);parent.addView(s,p);return s;}
    private EditText numeric(LinearLayout parent,String caption,String value){label(parent,caption,14,ink,true);EditText e=new EditText(this);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);e.setSingleLine(true);e.setText(value);e.setTextSize(18);e.setTextColor(ink);e.setPadding(dp(16),dp(8),dp(16),dp(8));e.setBackground(shape(surface,line));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.topMargin=dp(6);p.bottomMargin=dp(16);parent.addView(e,p);return e;}
    private void setup(boolean exam){screen("setup",exam?"開始模擬考":"自由練習",exam?"選好範圍，計時完成一份練習卷。":"每次作答後立即查看正確答案。");label(content,"報考地區",14,ink,true);Spinner city=spinner(content,QuizCore.CITIES,Arrays.asList(QuizCore.CITIES).indexOf(state.data.optString("city","基隆市")));label(content,"科目",14,ink,true);Spinner subject=spinner(content,new String[]{"地理環境","交通法規"},0);CheckBox joint=new CheckBox(this);joint.setText("五縣市配比：報考地區 60%，其他各 10%");joint.setTextColor(ink);joint.setTextSize(14);joint.setChecked(true);joint.setPadding(0,dp(6),0,dp(8));content.addView(joint);label(content,"此為練習出題設定；實際考試以報名單位公告為準。",11,muted,false);gap(content,16);EditText tf=numeric(content,"是非題數（可以填 0）",exam?"10":"5");EditText mc=numeric(content,"選擇題數（可以填 0）",exam?"40":"5");EditText minutes=exam?numeric(content,"測驗時間（分鐘）","30"):null;
        subject.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){joint.setEnabled(pos==0);joint.setAlpha(pos==0?1:.4f);}});
        button(content,"開始作答",true,()->{int nt=parseNumber(tf),nm=parseNumber(mc),time=exam?parseNumber(minutes):0;if(exam&&(time<1||time>180))throw new Exception("請設定 1～180 分鐘。");String region=(String)city.getSelectedItem();boolean law=subject.getSelectedItemPosition()==1;List<QuizCore.Question> selected=QuizCore.select(bank.questions,region,law,joint.isChecked(),nt,nm,new Random());String title=(law?"交通法規":joint.isChecked()?region+" · 五縣市":region)+(exam?"模擬考":"自由練習");startSession(selected,exam,time,title,region);});button(content,"返回首頁",false,()->home());}
    private int parseNumber(EditText e)throws Exception {try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){throw new Exception("題數與時間請填入整數。");}}
    private void startSession(List<QuizCore.Question> questions,boolean exam,int minutes,String title,String city){Action go=()->{state.active=new StudyState.Session(questions,exam,minutes,title);state.data.put("city",city);state.save();quiz();};if(state.active!=null)new AlertDialog.Builder(this).setTitle("開始新的練習？").setMessage("目前未交卷的練習會被這次取代；已完成的成績與錯題仍會保留。").setNegativeButton("繼續原練習",(d,w)->quiz()).setPositiveButton("開始新的",(d,w)->safely(go)).show();else safely(go);}
    private void challenge(){List<QuizCore.Question> list=new ArrayList<>();String city=state.data.optString("city","基隆市");for(QuizCore.Question q:bank.questions)if(q.city.equals(city)||q.city.equals("交通法規"))list.add(q);String day=new SimpleDateFormat("yyyyMMdd",Locale.ROOT).format(new Date());Collections.shuffle(list,new Random((day+city).hashCode()));startSession(list.subList(0,Math.min(5,list.size())),false,0,"每日 5 題挑戰",city);}
    private Set<String> currentWrong(){Set<String> ids=new HashSet<>(state.wrong);ids.retainAll(bank.byId.keySet());return ids;}
    private void updateBank(boolean manual){if(updating){if(manual)toast("題庫更新正在進行中。");return;}updating=true;if(manual)toast("正在比對題庫版本，舊題庫仍可使用。");final BankStore.Bank existing=bank;new Thread(()->{try{BankStore.Bank next=store.update(existing);runOnUiThread(()->{if(isDestroyed())return;bank=next;updating=false;safely(()->{state.data.put("lastCheck",System.currentTimeMillis());state.save();});if(manual)toast(existing.date.equals(next.date)?"已是最新題庫，共 "+next.questions.size()+" 題。":"題庫已更新，共 "+next.questions.size()+" 題。");if(page.equals("home"))home();});}catch(Exception e){runOnUiThread(()->{if(isDestroyed())return;updating=false;if(manual)toast("更新未完成："+e.getMessage()+"\n繼續使用已下載的題庫。");});}},"update-bank").start();}
    private void quiz(){if(state.active==null){home();return;}StudyState.Session s=state.active;if(s.exam&&s.deadline<=System.currentTimeMillis()){complete();return;}screen("quiz",s.title,"第 "+(s.index+1)+" 題，共 "+s.questions.size()+" 題");timer=label(content,s.exam?"剩餘 "+clock(s.deadline-System.currentTimeMillis()):"自由練習 · 不限時",15,s.exam?green:muted,true);int done=0;for(int a:s.answers)if(a>=0)done++;ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(s.questions.size());progress.setProgress(done);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(green));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(8));pp.topMargin=dp(10);pp.bottomMargin=dp(18);content.addView(progress,pp);
        QuizCore.Question q=s.questions.get(s.index);LinearLayout c=card(content,surface);label(c,q.label(),13,muted,false);gap(c,12);label(c,q.text,state.data.optInt("font",21),ink,true);gap(c,16);for(int n=0;n<q.choices;n++){final int choice=n;boolean picked=s.answers[s.index]==n;Button answer=button(c,q.tf?(n==0?"○  是":"×  否"):"選項 "+(n+1),picked,()->{int y=scroll.getScrollY();if(!s.exam&&s.answers[s.index]>=0)return;s.answers[s.index]=choice;state.save();quiz();scroll.post(()->scroll.scrollTo(0,y));});if(!s.exam&&s.answers[s.index]>=0){answer.setEnabled(false);if(n==q.answer){answer.setBackground(shape(green,0));answer.setTextColor(Color.WHITE);}else if(picked){answer.setBackground(shape(red,0));answer.setTextColor(Color.WHITE);}}}
        if(!s.exam&&s.answers[s.index]>=0){gap(c,12);boolean correct=s.answers[s.index]==q.answer;label(c,correct?"答對了！":"再記一次：正確答案是 "+q.answerLabel(),17,correct?green:red,true);}
        button(c,state.starred.contains(q.id)?"★ 已收藏（點一下取消）":"☆ 收藏這一題",false,()->{if(!state.starred.add(q.id))state.starred.remove(q.id);state.save();quiz();});LinearLayout controls=row(content);Button prev=button(controls,"上一題",false,()->{if(s.index>0)s.index--;state.save();quiz();});prev.setEnabled(s.index>0);button(controls,"下一題",true,()->{int next=QuizCore.nextUnanswered(s.answers,s.index);if(next<0){askFinish();return;}if(next==s.index)toast("只剩這一題尚未作答。");else if(next<s.index)toast("已跳回尚未作答的題目。");s.index=next;state.save();quiz();});button(content,"題號總覽 · 已答 "+done+" / "+s.questions.size(),false,()->questionGrid());button(content,"交卷並查看成績",false,()->askFinish());button(content,"儲存並返回首頁",false,()->{state.save();home();});if(s.exam)label(content,"離開畫面或關閉 App 時，模擬考計時仍會繼續。",12,muted,false);}
    private void questionGrid(){StudyState.Session s=state.active;ScrollView sc=new ScrollView(this);LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(12),dp(12),dp(12),dp(12));sc.addView(panel);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("選擇題號（黃色表示已作答）").setView(sc).setNegativeButton("關閉",null).create();LinearLayout r=null;for(int i=0;i<s.questions.size();i++){if(i%5==0)r=row(panel);final int index=i;Button b=button(r,String.valueOf(i+1),s.answers[i]>=0,()->{s.index=index;state.save();dialog.dismiss();quiz();});b.setTextSize(13);b.setPadding(0,dp(8),0,dp(8));}dialog.show();}
    private void askFinish(){if(state.active==null)return;int blank=0;for(int a:state.active.answers)if(a<0)blank++;new AlertDialog.Builder(this).setTitle("交卷？").setMessage(blank>0?"還有 "+blank+" 題未作答，交卷後會列為未答與待複習。":"所有題目都已作答，現在查看成績。").setNegativeButton("繼續作答",null).setPositiveButton("交卷",(d,w)->complete()).show();}
    private void complete(){if(state.active==null)return;safely(()->{lastFinished=state.active;JSONObject result=state.finish();result(result);});}
    private void result(JSONObject r){screen("result","練習完成","每一題的累積，都算數。");LinearLayout c=card(content,yellow);label(c,r.optInt("score")+" 分",48,Color.rgb(24,31,33),true);label(c,"答對 "+r.optInt("correct")+" / "+r.optInt("total")+" 題 · 未作答 "+r.optInt("unanswered")+" 題",15,Color.rgb(52,57,53),false);gap(c,12);label(c,"本次獲得 "+r.optInt("reward")+" 金幣",20,Color.rgb(24,31,33),true);label(c,"每題首次答對：1 顆星星＋3 枚金幣。",12,Color.rgb(52,57,53),false);button(content,"查看本次錯題",true,()->{bankMode="result";bankCity="全部地區";bankType=0;search="";bankPage=0;bank();});button(content,"再練一次",false,()->setup(false));button(content,"返回首頁",false,()->home());}
    private final List<QuizCore.Question> bankResults=new ArrayList<>();
    private void bank(){String title=bankMode.equals("wrong")?"錯題複習":bankMode.equals("starred")?"收藏題目":bankMode.equals("result")?"本次錯題":"查看題庫";screen("bank",title,"點題目卡片即可顯示或收起答案。");if(bankMode.equals("all")){LinearLayout filters=row(content);button(filters,"全部題庫",true,()->{});button(filters,"我的收藏",false,()->{bankMode="starred";bankPage=0;bank();});}else button(content,"返回全部題庫",false,()->{bankMode="all";bankPage=0;bank();});gap(content,10);
        LinkedHashSet<String> regions=new LinkedHashSet<>();regions.add("全部地區");regions.addAll(Arrays.asList(QuizCore.CITIES));regions.add("交通法規");for(QuizCore.Question q:bank.questions)regions.add(q.city);String[] cities=regions.toArray(new String[0]);Spinner city=spinner(content,cities,Arrays.asList(cities).indexOf(bankCity));Spinner type=spinner(content,new String[]{"全部題型","是非題","選擇題"},bankType);
        EditText query=new EditText(this);query.setSingleLine(true);query.setTextSize(16);query.setTextColor(ink);query.setHintTextColor(muted);query.setHint("搜尋路名、地標或題目關鍵字");query.setPadding(dp(12),dp(10),dp(12),dp(10));query.setBackground(shape(surface,line));query.setText(search);content.addView(query,new LinearLayout.LayoutParams(-1,dp(52)));gap(content,12);questionCount=label(content,"",13,muted,false);gap(content,12);questionList=new LinearLayout(this);questionList.setOrientation(LinearLayout.VERTICAL);content.addView(questionList,new LinearLayout.LayoutParams(-1,-2));
        query.addTextChangedListener(new TextWatcher(){Runnable pending;public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){search=s.toString();bankPage=0;if(pending!=null)handler.removeCallbacks(pending);pending=()->{if(page.equals("bank"))filterBank();};handler.postDelayed(pending,220);}public void afterTextChanged(Editable s){}});
        city.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int position,long id){String selected=cities[position];if(!selected.equals(bankCity)){bankCity=selected;bankPage=0;}filterBank();}});type.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int position,long id){if(bankType!=position){bankType=position;bankPage=0;}filterBank();}});filterBank();}
    private void filterBank(){if(questionList==null||!page.equals("bank"))return;bankResults.clear();List<QuizCore.Question> source=bank.questions;if(bankMode.equals("result")&&lastFinished!=null){source=new ArrayList<>();for(int i=0;i<lastFinished.questions.size();i++)if(lastFinished.answers[i]!=lastFinished.questions.get(i).answer)source.add(lastFinished.questions.get(i));}
        for(QuizCore.Question q:source){if(!bankCity.equals("全部地區")&&!q.city.equals(bankCity))continue;if(bankType==1&&!q.tf||bankType==2&&q.tf)continue;if(!q.text.toLowerCase(Locale.ROOT).contains(search.toLowerCase(Locale.ROOT)))continue;if(bankMode.equals("wrong")&&!state.wrong.contains(q.id))continue;if(bankMode.equals("starred")&&!state.starred.contains(q.id))continue;bankResults.add(q);}
        int pages=Math.max(1,(bankResults.size()+29)/30);bankPage=Math.min(bankPage,pages-1);questionCount.setText("共 "+bankResults.size()+" 題 · 第 "+(bankPage+1)+" / "+pages+" 頁 · 每頁 30 題");questionList.removeAllViews();if(bankResults.isEmpty()){LinearLayout c=card(questionList,surface);label(c,bankMode.equals("wrong")?"這個範圍目前沒有錯題。":"沒有符合條件的題目。",18,ink,true);label(c,"可以更換地區、題型或清除搜尋文字。",13,muted,false);return;}
        for(int i=bankPage*30;i<Math.min(bankResults.size(),bankPage*30+30);i++)questionCard(bankResults.get(i));LinearLayout r=row(questionList);Button prev=button(r,"上一頁",false,()->{bankPage--;filterBank();scroll.smoothScrollTo(0,0);});prev.setEnabled(bankPage>0);Button next=button(r,"下一頁",true,()->{bankPage++;filterBank();scroll.smoothScrollTo(0,0);});next.setEnabled(bankPage+1<pages);}
    private void questionCard(QuizCore.Question q){LinearLayout c=card(questionList,surface);label(c,q.label(),12,muted,false);gap(c,8);TextView body=label(c,q.text,state.data.optInt("font",21)-2,ink,false);gap(c,8);TextView answer=label(c,"正確答案："+q.answerLabel(),18,green,true);answer.setVisibility(View.GONE);TextView tip=label(c,"點此卡片顯示答案",11,muted,false);c.setOnClickListener(v->{boolean show=answer.getVisibility()!=View.VISIBLE;answer.setVisibility(show?View.VISIBLE:View.GONE);tip.setText(show?"再點一下收起答案":"點此卡片顯示答案");safely(()->{state.data.put("lastRead",q.id);state.save();});});LinearLayout actions=row(c);Button star=button(actions,state.starred.contains(q.id)?"★ 已收藏":"☆ 收藏",false,()->{if(!state.starred.add(q.id))state.starred.remove(q.id);state.save();filterBank();});star.setTextSize(13);if(bankMode.equals("wrong")){Button remove=button(actions,"已記住，移除",false,()->{state.wrong.remove(q.id);state.save();filterBank();});remove.setTextSize(13);}}
    private void garage(){screen("garage","我的車庫","答題賺金幣，慢慢打造自己的小黃。");LinearLayout c=card(content,surface);label(c,"錢包 "+state.data.optInt("coins")+" 金幣 · "+state.earned.size()+" 顆星星",20,ink,true);c.addView(new TaxiView(this,true),new LinearLayout.LayoutParams(-1,dp(200)));label(c,"車身顏色免費選擇",14,muted,false);LinearLayout colors=row(c);String[] names={"小黃","白色","深藍","紅色"};String[] values={"#FFD33D","#F2F3F2","#41658C","#D46860"};for(int i=0;i<names.length;i++){final int n=i;Button b=button(colors,names[i],values[i].equals(state.data.optString("carColor","#FFD33D")),()->{state.data.put("carColor",values[n]);state.save();garage();});b.setTextSize(12);b.setPadding(0,dp(10),0,dp(10));}
        label(content,"配件商店",21,ink,true);gap(content,10);String[] ids={"dashcam","drink","amulet","cat","scent","wheel"};String[] items={"行車紀錄器","提神飲料","平安符","招財貓","車用擴香","運動方向盤"};int[] prices={150,60,80,150,100,220};for(int i=0;i<ids.length;i++){final int n=i;LinearLayout item=card(content,surface);label(item,items[i],18,ink,true);label(item,state.owned.contains(ids[i])?"已安裝在車內":prices[i]+" 金幣",13,muted,false);Button buy=button(item,state.owned.contains(ids[i])?"已擁有":"購買並安裝",!state.owned.contains(ids[i]),()->{if(state.owned.contains(ids[n]))return;int coins=state.data.optInt("coins");if(coins<prices[n]){toast("還差 "+(prices[n]-coins)+" 金幣，答對尚未掌握的題目即可獲得。");return;}state.owned.add(ids[n]);state.data.put("coins",coins-prices[n]);state.save();garage();});buy.setEnabled(!state.owned.contains(ids[i]));}label(content,"金幣只靠答題獲得，沒有現金交易。此版車庫為平面預覽。",12,muted,false);}
    private void me(){screen("me","我的學習","成績與收藏儲存在這支手機。");int attempts=state.data.optInt("attempts"),correct=state.data.optInt("correct");LinearLayout c=card(content,surface);label(c,"累計作答 "+attempts+" 題",22,ink,true);label(c,"累計正確率 "+(attempts==0?"—":Math.round(correct*100f/attempts)+"%")+" · 掌握 "+state.earned.size()+" 題",14,muted,false);button(c,"查看錯題（"+currentWrong().size()+"）",false,()->{bankMode="wrong";bankCity="全部地區";bankType=0;search="";bankPage=0;bank();});button(c,"查看收藏（"+state.starred.size()+"）",false,()->{bankMode="starred";bankCity="全部地區";bankType=0;search="";bankPage=0;bank();});String last=state.data.optString("lastRead","");if(bank.byId.containsKey(last))button(c,"接著上次閱讀",true,()->{QuizCore.Question q=bank.byId.get(last);bankMode="all";bankCity=q.city;bankType=q.tf?1:2;search="";bankPage=(q.number-1)/30;bank();});
        LinearLayout settings=card(content,surface);label(settings,"閱讀設定",18,ink,true);Switch night=new Switch(this);night.setText("夜間模式");night.setTextColor(ink);night.setTextSize(16);night.setChecked(state.data.optBoolean("night"));night.setPadding(0,dp(16),0,dp(16));settings.addView(night);night.setOnCheckedChangeListener((v,value)->safely(()->{state.data.put("night",value);state.save();buildShell();me();}));label(settings,"題目字體大小",13,muted,false);int[] sizes={18,21,25,29};int selected=1;for(int i=0;i<sizes.length;i++)if(sizes[i]==state.data.optInt("font",21))selected=i;Spinner font=spinner(settings,new String[]{"小","標準","大","特大"},selected);font.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int i,long id){if(state.data.optInt("font",21)!=sizes[i])safely(()->{state.data.put("font",sizes[i]);state.save();});}});
        LinearLayout backup=card(content,surface);label(backup,"學習紀錄備份",18,ink,true);label(backup,"換手機或移除 App 前先匯出備份。此版尚未提供帳號與跨裝置自動同步。",13,muted,false);button(backup,"匯出備份檔",false,()->{state.save();Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/json");intent.putExtra(Intent.EXTRA_TITLE,"taxi-study-backup-"+new SimpleDateFormat("yyyyMMdd",Locale.ROOT).format(new Date())+".json");startActivityForResult(intent,41);});button(backup,"從備份檔還原",false,()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/json");startActivityForResult(intent,42);});
        label(content,"最近的測驗",21,ink,true);gap(content,12);JSONArray history=state.history();if(history.length()==0)label(content,"完成第一份練習，就會在這裡看到成績。",14,muted,false);for(int i=0;i<Math.min(history.length(),30);i++){JSONObject r=history.optJSONObject(i);if(r==null)continue;LinearLayout h=card(content,surface);label(h,r.optInt("score")+" 分 · "+r.optString("title"),18,ink,true);label(h,date(r.optLong("time"))+" · "+r.optInt("correct")+" / "+r.optInt("total")+" 題答對",13,muted,false);}
        gap(content,14);label(content,"計程車考照 0.1.0 · Android 測試版",13,muted,true);label(content,"只申請網路權限，用於題庫更新。作答紀錄不會傳送到伺服器。資料來源：內政部警政署題庫；本 App 與政府機關無隸屬或合作關係。",12,muted,false);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;if(request==41)safely(()->{try(OutputStream out=getContentResolver().openOutputStream(data.getData())){if(out==null)throw new IOException("無法開啟備份位置");state.save();out.write(state.data.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));}toast("備份已匯出。");});if(request==42)safely(()->{String backup=BankStore.read(getContentResolver().openInputStream(data.getData()),15*1024*1024);JSONObject snapshot=new JSONObject(backup);if(!snapshot.optString("app").equals("tw.cmlove.taxiexam.preview"))throw new IOException("這不是計程車考照的備份檔。");new AlertDialog.Builder(this).setTitle("還原學習紀錄？").setMessage("目前手機的成績、錯題、金幣與進行中的測驗，會由備份檔取代。").setNegativeButton("取消",null).setPositiveButton("還原",(d,w)->safely(()->{state.restore(snapshot);buildShell();me();toast("學習紀錄已還原。");})).show();});}
    @Override public void onBackPressed(){if(page.equals("quiz")&&state.active!=null){new AlertDialog.Builder(this).setTitle("儲存並離開？").setMessage(state.active.exam?"模擬考的計時會繼續，下次可接著作答。":"下次可以接著這一題繼續練習。").setNegativeButton("繼續作答",null).setPositiveButton("儲存並離開",(d,w)->{persist();home();}).show();}else if(!page.equals("home"))home();else super.onBackPressed();}
    private final class TaxiView extends View {
        private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private final boolean interior;
        TaxiView(Context context,boolean interior){super(context);this.interior=interior;setContentDescription(interior?"可自選顏色與安裝配件的平面車庫":"計程車插畫");}
        private void rect(Canvas c,float l,float t,float r,float b,int color,float radius){paint.setColor(color);c.drawRoundRect(l,t,r,b,radius,radius,paint);}
        private void word(Canvas c,String text,float x,float y,int size,int color){paint.setColor(color);paint.setTextSize(size);paint.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));c.drawText(text,x,y,paint);}
        @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);Canvas c=canvas;float sx=getWidth()/340f,sy=getHeight()/(interior?220f:145f);c.save();c.scale(sx,sy);int dark=Color.rgb(28,39,42),car=Color.parseColor(state.data.optString("carColor","#FFD33D"));
            if(!interior){rect(c,12,113,328,118,Color.rgb(223,180,32),2);rect(c,44,56,294,104,dark,16);Path roof=new Path();roof.moveTo(86,61);roof.lineTo(114,27);roof.lineTo(228,27);roof.lineTo(261,61);roof.close();paint.setColor(dark);c.drawPath(roof,paint);rect(c,122,33,177,55,Color.rgb(255,228,120),5);rect(c,184,33,224,55,Color.rgb(255,228,120),5);rect(c,148,12,195,27,dark,4);word(c,"TAXI",155,23,11,yellow);paint.setColor(dark);c.drawCircle(97,102,22,paint);c.drawCircle(246,102,22,paint);paint.setColor(Color.rgb(235,237,227));c.drawCircle(97,102,10,paint);c.drawCircle(246,102,10,paint);rect(c,52,70,70,80,yellow,3);rect(c,272,70,287,80,yellow,3);word(c,"上路前，先練好",114,85,13,yellow);}
            else{rect(c,0,4,340,218,dark,18);rect(c,12,14,328,115,Color.rgb(215,233,227),10);Path road=new Path();road.moveTo(135,42);road.lineTo(205,42);road.lineTo(276,115);road.lineTo(66,115);road.close();paint.setColor(Color.rgb(131,148,145));c.drawPath(road,paint);rect(c,168,55,173,71,Color.WHITE,1);rect(c,168,88,174,108,Color.WHITE,1);rect(c,12,122,328,154,car,10);rect(c,148,168,227,200,Color.rgb(48,61,61),4);word(c,"TAXI  085",156,188,12,Color.rgb(123,224,162));paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(state.owned.contains("wheel")?13:10);paint.setColor(state.owned.contains("wheel")?Color.rgb(230,76,60):Color.rgb(124,139,139));c.drawCircle(85,174,32,paint);paint.setStrokeWidth(7);c.drawLine(55,172,115,172,paint);c.drawLine(85,174,85,203,paint);paint.setStyle(Paint.Style.FILL);rect(c,143,19,197,32,dark,3);
                if(state.owned.contains("dashcam")){rect(c,216,18,244,34,dark,4);paint.setColor(Color.rgb(240,80,66));c.drawCircle(239,23,2,paint);}if(state.owned.contains("amulet")){rect(c,183,36,187,65,Color.rgb(159,75,58),0);rect(c,176,63,195,89,Color.rgb(198,71,53),3);word(c,"安",179,81,12,yellow);}if(state.owned.contains("cat")){rect(c,273,100,297,128,yellow,9);paint.setColor(yellow);c.drawCircle(278,102,7,paint);c.drawCircle(292,102,7,paint);word(c,"招",278,119,13,dark);}if(state.owned.contains("drink")){rect(c,262,169,280,199,Color.rgb(223,78,61),4);word(c,"醒",265,188,12,Color.WHITE);}if(state.owned.contains("scent")){rect(c,234,121,250,142,Color.rgb(118,164,166),4);rect(c,238,115,246,122,Color.rgb(51,93,94),2);}
            }c.restore();}
    }
}
