package tw.cmlove.taxiexam;

import android.content.Context;
import org.json.*;
import java.util.*;
import java.util.regex.*;
import java.nio.charset.StandardCharsets;

/** Native equivalent of question-explanations/evidence and memory classification in Site v71. */
public final class StudyGuide {
    public final JSONObject data,guides;
    private final JSONObject reviewed;
    private final Map<String,String> reviewedIds=new HashMap<>(),sourceKeys=new HashMap<>();
    private final Map<String,Pattern> patterns=new HashMap<>();
    private final Map<String,List<QuizCore.Question>> regions=new HashMap<>();
    private final Map<String,Map<String,QuizCore.Question>> indexes=new HashMap<>();
    private final Map<String,JSONObject> cache=new HashMap<>();
    private static final String EXCEPTION="(不正確|不符合|錯誤|何者為非|何者非|何者不是|不包括|不屬於|未經過|不在|不位於)";
    private static final String DIRECTION="(單行道|同方向|反方向|往東|往西|往南|往北|東向|西向|南向|北向|左轉|右轉|順向|逆向)";
    private static final String AGENCY="(警察局|分局|派出所|市政府|縣政府|區公所|鄉公所|鎮公所|地政事務所|監理站|法院|檢察署|消防局|戶政事務所)";
    public StudyGuide(Context context,List<QuizCore.Question> questions)throws Exception{
        data=new JSONObject(BankStore.read(context.getAssets().open("study-data.json"),2*1024*1024));guides=data.getJSONObject("guides");reviewed=data.getJSONObject("reviewed");
        JSONObject sources=reviewed.getJSONObject("sources");Iterator<String> it=sources.keys();while(it.hasNext()){String id=it.next(),key=key(sources.getJSONObject(id));reviewedIds.put(key,id);sourceKeys.put(id,key);}setBank(questions);
    }
    public void setBank(List<QuizCore.Question> questions){regions.clear();indexes.clear();cache.clear();for(QuizCore.Question q:questions)regions.computeIfAbsent(q.webRegion(),x->new ArrayList<>()).add(q);for(Map.Entry<String,List<QuizCore.Question>> entry:regions.entrySet()){entry.getValue().sort(Comparator.comparing((QuizCore.Question q)->!q.tf).thenComparingInt(q->q.number));Map<String,QuizCore.Question> index=new HashMap<>();for(QuizCore.Question q:entry.getValue())index.put(key(q),q);indexes.put(entry.getKey(),index);}}
    private boolean matches(String pattern,String text){return patterns.computeIfAbsent(pattern,Pattern::compile).matcher(text).find();}
    public static String normalize(String value){return value.replaceAll("[\\s，,。．「」『』：:？?、；;]","");}
    private static String key(QuizCore.Question q){StringBuilder s=new StringBuilder(q.webRegion()).append('|').append(q.type()).append('|').append(normalize(q.stem)).append('|').append(q.answerValue());for(int i=0;i<q.options.size();i++)s.append('|').append(i+1).append('=').append(normalize(q.options.get(i)));return s.toString();}
    private static String key(JSONObject q)throws JSONException{StringBuilder s=new StringBuilder(q.getString("region")).append('|').append(q.getString("type")).append('|').append(normalize(q.getString("question"))).append('|').append(q.getString("answer"));JSONObject options=q.optJSONObject("options");if(options!=null){List<String> keys=new ArrayList<>();Iterator<String> it=options.keys();while(it.hasNext())keys.add(it.next());Collections.sort(keys);for(String k:keys)s.append('|').append(k).append('=').append(normalize(options.getString(k)));}return s.toString();}
    public static JSONObject webQuestion(QuizCore.Question q)throws JSONException{JSONObject j=new JSONObject().put("id",q.webId()).put("region",q.webRegion()).put("type",q.type()).put("question",q.stem).put("answer",q.answerValue());if(!q.tf){JSONObject options=new JSONObject();for(int i=0;i<q.options.size();i++)options.put(String.valueOf(i+1),q.options.get(i));j.put("options",options);}return j;}
    public JSONArray topics(QuizCore.Question q)throws JSONException{
        JSONArray result=new JSONArray();String text=q.searchText();JSONObject guide=guides.optJSONObject(q.webRegion());if(guide!=null){JSONArray chapters=guide.getJSONArray("chapters");for(int i=0;i<chapters.length();i++){JSONObject c=chapters.getJSONObject(i);if(matches(c.getString("matcher"),text))result.put(c.getString("id"));}}
        else if(q.webRegion().equals("交通法令")){String selected="other";int highest=0;JSONArray priority=data.getJSONArray("trafficPriority");JSONObject keywords=data.getJSONObject("trafficKeywords");for(int i=0;i<priority.length();i++){String id=priority.getString(i);JSONArray words=keywords.getJSONArray(id);int score=0;for(int n=0;n<words.length();n++)if(text.contains(words.getString(n)))score++;if(score>highest){highest=score;selected=id;}}result.put(selected);}return result;
    }
    public JSONArray chapters(String region){JSONObject guide=guides.optJSONObject(region.equals("交通法規")?"交通法令":region);return guide!=null?guide.optJSONArray("chapters"):region.equals("交通法規")?data.optJSONArray("trafficCategories"):new JSONArray();}
    public JSONObject chapter(String region,String id)throws JSONException{JSONArray chapters=chapters(region);for(int i=0;i<chapters.length();i++)if(chapters.getJSONObject(i).getString("id").equals(id))return chapters.getJSONObject(i);return new JSONObject();}
    public boolean inTopic(QuizCore.Question q,String id){if(id.equals("all"))return true;try{JSONArray t=topics(q);for(int i=0;i<t.length();i++)if(t.getString(i).equals(id))return true;}catch(Exception ignored){}return false;}
    private List<QuizCore.Question> resolve(JSONArray ids,String region)throws JSONException{List<QuizCore.Question> list=new ArrayList<>();Map<String,QuizCore.Question> index=indexes.getOrDefault(region,Collections.emptyMap());for(int i=0;i<ids.length();i++){QuizCore.Question q=index.get(sourceKeys.get(ids.getString(i)));if(q==null)return null;list.add(q);}return list;}
    private static JSONArray qArray(List<QuizCore.Question> list)throws JSONException{JSONArray array=new JSONArray();for(QuizCore.Question q:list)array.put(webQuestion(q));return array;}
    private static Set<String> bigrams(String text){Set<String> s=new HashSet<>();for(int i=0;i<text.length()-1;i++)s.add(text.substring(i,i+2));return s;}
    public JSONObject explanation(QuizCore.Question q)throws JSONException{
        JSONObject known=cache.get(q.id);if(known!=null)return known;
        List<QuizCore.Question> all=regions.getOrDefault(q.webRegion(),Collections.emptyList());String full=q.searchText(),id=reviewedIds.get(key(q));JSONObject notes=reviewed.getJSONObject("notes"),note=id==null?null:notes.optJSONObject(id);List<QuizCore.Question> sources=note==null?new ArrayList<>():resolve(note.getJSONArray("sourceIds"),q.webRegion());boolean current=note!=null&&sources!=null&&!sources.isEmpty();boolean needsReview=!current&&(note!=null||notes.has(q.webId()));JSONArray comparisons=new JSONArray();
        if(current){JSONArray groups=reviewed.getJSONArray("groups"),groupIds=note.getJSONArray("groupIds");Set<String> wanted=new HashSet<>();for(int i=0;i<groupIds.length();i++)wanted.add(groupIds.getString(i));for(int i=0;i<groups.length();i++){JSONObject group=groups.getJSONObject(i);if(!wanted.contains(group.getString("id")))continue;JSONArray rows=group.getJSONArray("rows"),valid=new JSONArray();for(int j=0;j<rows.length();j++){JSONObject row=rows.getJSONObject(j);List<QuizCore.Question> found=resolve(row.getJSONArray("sourceIds"),q.webRegion());if(found!=null)valid.put(new JSONObject(row.toString()).put("sources",qArray(found)));}if(valid.length()>1)comparisons.put(new JSONObject().put("id",group.getString("id")).put("title",group.getString("title")).put("prompt",group.getString("prompt")).put("rows",valid));}}
        else{note=null;sources=new ArrayList<>();}
        String correctionText=null,correctionAnswer=null;List<QuizCore.Question> correctionSources=new ArrayList<>();
        if(q.tf&&q.answer==1&&indexes.getOrDefault(q.webRegion(),Collections.emptyMap()).containsKey(key(q))){String text=normalize(q.stem),wrong=null;Set<String> answers=new HashSet<>();for(QuizCore.Question candidate:all){if(candidate.tf||matches(EXCEPTION,candidate.stem))continue;String stem=normalize(candidate.stem),answer=candidate.options.get(candidate.answer);if(stem.length()<8||!text.startsWith(stem)||answer.isEmpty()||matches("(以上|皆是|皆非|均可|均是|全部|二者|兩者|三者)",answer))continue;String tail=text.substring(stem.length());for(int n=0;n<candidate.options.size();n++){String option=candidate.options.get(n),norm=normalize(option);if(n!=candidate.answer&&norm.length()>=2&&(tail.equals(norm)||tail.equals(norm+"上"))&&!normalize(answer).equals(norm)){if(correctionAnswer==null){correctionAnswer=answer;wrong=option;}answers.add(normalize(answer));correctionSources.add(candidate);break;}}}if(answers.size()==1)correctionText="題幹寫「"+wrong+"」；相同題幹的選擇題確認應為「"+correctionAnswer+"」。";else{correctionAnswer=null;correctionSources.clear();}}
        boolean specific=note!=null||correctionText!=null,exception=matches(EXCEPTION,q.stem);
        String takeaway=!q.tf?(exception?"本題要找不符合題意的項目":"正確選項")+"："+q.answerLabel()+"。":q.answer==0?"題幹敘述正確；回想時要保留其中的路段、方向與限制條件。":correctionAnswer!=null?"應記住的正確內容："+correctionAnswer+"。":"題幹敘述不成立；不要把錯誤句子直接背成事實。";
        String recall=note!=null&&!note.optString("recall").isEmpty()?note.getString("recall"):matches(DIRECTION,full)?"遮住答案，先說出來向、路口，再說行進方向或轉彎限制。":matches(AGENCY,full)?"遮住選項，說出完整機關名稱及本題考的位置或業務。":"遮住答案，用自己的話說出題目條件與正確答案。";
        List<String> tips=new ArrayList<>(),shared=new ArrayList<>();if(exception)shared.add("先圈出「非、不、未、無須」等否定詞，再逐一排除符合敘述的選項，避免把題意看反。");
        String summary=note!=null?note.getString("text"):correctionText;
        if(q.webRegion().equals("交通法令")){
            Matcher numbers=Pattern.compile("\\d[\\d,.]*(?:\\s*(?:元|日|天|年|月|小時|分鐘|分|公尺|公里|次|點))?").matcher(q.tf?q.stem:q.stem+" "+q.options.get(q.answer));LinkedHashSet<String> tokens=new LinkedHashSet<>();while(numbers.find())tokens.add(numbers.group());if(!tokens.isEmpty()){List<String> first=new ArrayList<>(tokens);shared.add(q.tf&&q.answer==1?"這題含數字條件，但題幹為錯誤敘述；先核對正確條件，再背期限、金額或距離。":"本題"+(exception?"選出的不符合項目":"正確作答")+"涉及數字條件（"+String.join("、",first.subList(0,Math.min(3,first.size())))+"）；要連同適用情況一起記。");}
            JSONObject category=chapter("交通法規",topics(q).getString(0));if(q.tf&&q.answer==1)shared.add("答案為「否」時，回頭找題幹被偷換的期限、金額、行車動作或主管機關名稱。");tips.add(category.getString("description"));if(summary==null)summary="本題屬於「"+category.getString("label")+"」，依題庫正確答案為 "+q.answerLabel()+"。";
        }else if(guides.has(q.webRegion())){
            JSONArray ids=topics(q);List<String> names=new ArrayList<>(),descriptions=new ArrayList<>();for(int i=0;i<Math.min(2,ids.length());i++){JSONObject c=chapter(q.city,ids.getString(i));names.add(c.getString("label"));tips.add("口訣："+c.getString("mnemonic"));descriptions.add(c.getString("description"));}tips.addAll(descriptions);if(matches(DIRECTION,full))shared.add("方向題先固定道路與行進方向，再判斷同向、反向或轉彎；不要只記單一路名。");if(matches(AGENCY,full))shared.add("行政機關題要把「機關名稱＋所在道路＋鄰近地標」綁成同一個位置錨點。");if(summary==null)summary=names.isEmpty()?"這是"+q.webRegion()+"地理題，依題庫正確答案為 "+q.answerLabel()+"。":"本題歸入「"+String.join("／",names)+"」，依題庫正確答案為 "+q.answerLabel()+"。";
        }else{if(summary==null)summary="依題庫正確答案為 "+q.answerLabel()+"。";tips.add(matches("(不正確|錯誤|不在|不位於|未經過|無須|不得|非下列|何者為非|何者錯誤)",full)?"先圈否定詞，再用行政區、道路與地標三個線索逐一排除。":"把行政區、道路與地標綁在一起記，遇到相似路名時先判斷所在縣市。");}
        tips.addAll(shared);LinkedHashSet<String> unique=new LinkedHashSet<>(tips);JSONArray memoryTips=new JSONArray();for(String tip:unique){if(memoryTips.length()==4)break;memoryTips.put(tip);}
        Set<String> tokens=bigrams(normalize(q.stem));Map<QuizCore.Question,Double> similarities=new HashMap<>();List<QuizCore.Question> related=new ArrayList<>();for(QuizCore.Question other:all){if(other.webId().equals(q.webId()))continue;Set<String> theirs=bigrams(normalize(other.stem));int sharedCount=0;for(String token:tokens)if(theirs.contains(token))sharedCount++;double score=2.0*sharedCount/Math.max(1,tokens.size()+theirs.size());if(score>=.76){related.add(other);similarities.put(other,score);}}related.sort((a,b)->Double.compare(similarities.get(b),similarities.get(a)));
        JSONObject result=new JSONObject().put("answerLabel",q.answerLabel()).put("summary",summary).put("memoryTips",memoryTips).put("takeaway",takeaway).put("recallPrompt",recall).put("sources",qArray(note!=null?sources:correctionSources)).put("comparisons",comparisons).put("relatedQuestions",qArray(related.subList(0,Math.min(2,related.size())))).put("needsReview",needsReview).put("hasSpecificExplanation",specific);
        if(cache.size()>200)cache.clear();cache.put(q.id,result);return result;
    }
    /** Canonical encoding shared only by the independent website oracle test. */
    public static String canonical(Object v)throws JSONException{if(v instanceof JSONObject){JSONObject o=(JSONObject)v;TreeSet<String> keys=new TreeSet<>();Iterator<String> it=o.keys();while(it.hasNext())keys.add(it.next());StringBuilder b=new StringBuilder("{");for(String k:keys)b.append(canonical(k)).append(canonical(o.get(k)));return b.append('}').toString();}if(v instanceof JSONArray){JSONArray a=(JSONArray)v;StringBuilder b=new StringBuilder("[");for(int i=0;i<a.length();i++)b.append(canonical(a.get(i)));return b.append(']').toString();}String s=String.valueOf(v);return s.length()+":"+s;}
    public JSONObject verify(List<QuizCore.Question> all,JSONObject expected)throws Exception{int checked=0;for(QuizCore.Question q:all){if(!expected.has(q.webId()))continue;JSONObject actual=new JSONObject().put("q",webQuestion(q)).put("chapters",topics(q)).put("explanation",explanation(q));String hash=QuizCore.sha256(canonical(actual).getBytes(StandardCharsets.UTF_8));if(!hash.equals(expected.getString(q.webId())))return new JSONObject().put("passed",false).put("mismatch",q.webId()).put("actual",actual);checked++;}return new JSONObject().put("passed",checked==expected.length()).put("checked",checked);}
}
